[package]
name = "merge_exports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matfile = "0.3.1"
hdf5 = "0.8.1"
